Car hire smoke test implementing in process.
TA-user/RyanAir_Test_Automation pull request #40
Opened 2022-01-17 07:47 UTC by kit-91-daniil

Fix utils.text_formatter.TextFormatter.format_date_time documentation.

Implement smoke test for car hire

Prepare for rebase

2022-01-17 08:30 UTC, EgorSolenok commented on utils/browser_helper.py
> +from selenium.webdriver.common.by import By
duplicate

2022-01-17 08:30 UTC, EgorSolenok approved these changes
Good job!

2022-01-19 08:54 UTC, yefim-mironyuk approved these changes

2022-01-19 08:54 UTC, yefim-mironyuk commented on utils/logging.py
> +                          enqueue=True,
No need in enqueue

2022-01-19 09:11 UTC, EgorSolenok requested changes

2022-01-19 09:11 UTC, relaxing-observer commented on config.py
> +    WAIT_TIME_SECS = 13
Is that correct? Do we have place where we need to wait 13 sec?

2022-01-19 09:11 UTC, relaxing-observer commented on tests/car_search_tests/test_car_search.py
> +        assertions = Assertions(main_page.browser)
We use assertions as a fixture in coftest. I suppose that you should to remove that line

2022-01-19 09:11 UTC, relaxing-observer commented on tests/pages/main_page.py
>      def choose_date(self, date: str):
It's a duplicate method from class MainPage. As I remember, we decided to move this method to MainPage class from MainPageCarHireTab

2022-01-19 09:11 UTC, EgorSolenok commented on tests/pages/main_page.py
>          self.choose_date(date)
MainPage.choose_date(self, date)
and etc below in class

2022-01-19 09:11 UTC, EgorSolenok commented on tests/car_search_tests/test_car_search.py
> +        assertions.element_should_contain_value(CarHireTabLocators.HEADER_TITLE, "Car Hire")
Maybe we should throw out "Car hire" to test data as parameter?

2022-01-19 09:11 UTC, EgorSolenok commented on utils/text_formatter.py
>      def date_formatter(cls, date_str: str) -> formatted_date_nt:
maybe format_date name?  you said about it yesterday

2022-01-19 09:12 UTC, yefim-mironyuk commented on config.py
> +    WAIT_TIME_SECS = 13
> Is that correct? Do we have place where we need to wait 13 sec?

Why not. Maybe someone will run this test with slow internet connection)

2022-01-19 10:47 UTC, yefim-mironyuk approved these changes

2022-01-19 10:54 UTC, EgorSolenok approved these changes

2022-01-19 11:00 UTC, TA-user approved these changes

2022-01-19 11:00 UTC, merged