switch tab method implemented
TA-user/RyanAir_Test_Automation pull request #58
Opened 2022-01-24 14:37 UTC by yefim-mironyuk

2022-01-24 14:39 UTC, EgorSolenok approved these changes

2022-01-24 14:50 UTC, TA-user requested changes

2022-01-24 14:50 UTC, TA-user commented on tests/pages/hotel_page.py
> +        self.element_interactions.switch_to_tab("NEW")
enum should be used, not strings

2022-01-24 14:58 UTC, TA-user requested changes

2022-01-24 14:58 UTC, TA-user commented on utils/browser_helper.py
> +    class Tabs(Enum):
put it outside of ElementInteractions

2022-01-25 10:41 UTC, TA-user approved these changes

2022-01-25 10:49 UTC, kit-91-daniil approved these changes

2022-01-25 10:49 UTC, merged